/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_convocraft_commandProcessor_profanityFilter */

#ifndef _Included_com_convocraft_commandProcessor_profanityFilter
#define _Included_com_convocraft_commandProcessor_profanityFilter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_convocraft_commandProcessor_profanityFilter
 * Method:    filterProfanityRetainingWhitespace
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_convocraft_commandProcessor_profanityFilter_filterProfanityRetainingWhitespace
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
